# Generated by Django 3.2 on 2021-04-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210419_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(default='Programming', to='blog.Category'),
        ),
    ]
